/**
 * Device Profile Catalog
 * Perfis de celulares reais para spoofing de hardware.
 * Cada perfil injeta configurações no config.ini do AVD
 * e sobrescreve o build.prop via ADB após o boot.
 */

const DEVICE_PROFILES = {
  'samsung-s23': {
    id: 'samsung-s23',
    label: 'Samsung Galaxy S23',
    brand: 'samsung',
    manufacturer: 'samsung',
    model: 'SM-S911B',
    product: 'dm1q',
    device: 'dm1q',
    board: 'kalama',
    hardware: 'qcom',
    // Definido pelo avdmanager --device
    avdDevice: 'pixel_6',
    screenDpi: 393,
    screenWidth: 1080,
    screenHeight: 2340,
    ram: 8192,
    // build.prop overrides (aplicados via ADB após boot)
    buildProps: {
      'ro.product.brand':            'samsung',
      'ro.product.manufacturer':     'samsung',
      'ro.product.model':            'SM-S911B',
      'ro.product.name':             'dm1q',
      'ro.product.device':           'dm1q',
      'ro.product.board':            'kalama',
      'ro.hardware':                 'qcom',
      'ro.build.fingerprint':        'samsung/dm1qxxx/dm1q:13/TP1A.220624.014/S911BXXU3CWC1:user/release-keys',
      'ro.build.description':        'dm1q-user 13 TP1A.220624.014 S911BXXU3CWC1 release-keys',
      'ro.build.display.id':         'TP1A.220624.014.S911BXXU3CWC1',
      'ro.build.id':                 'TP1A.220624.014',
      'ro.build.version.incremental':'S911BXXU3CWC1',
      'ro.build.tags':               'release-keys',
      'ro.build.type':               'user',
      'ro.build.user':               'dpi',
      'ro.build.host':               'SWDK9605',
      'ro.build.flavor':             'dm1qxxx-user',
      'ro.boot.hardware':            'qcom',
      'ro.product.cpu.abi':          'arm64-v8a',
    },
  },

  'xiaomi-13': {
    id: 'xiaomi-13',
    label: 'Xiaomi 13',
    brand: 'Xiaomi',
    manufacturer: 'Xiaomi',
    model: '2211133C',
    product: 'fuxi',
    device: 'fuxi',
    board: 'taro',
    hardware: 'qcom',
    avdDevice: 'pixel_6',
    screenDpi: 413,
    screenWidth: 1080,
    screenHeight: 2400,
    ram: 8192,
    buildProps: {
      'ro.product.brand':            'Xiaomi',
      'ro.product.manufacturer':     'Xiaomi',
      'ro.product.model':            '2211133C',
      'ro.product.name':             'fuxi',
      'ro.product.device':           'fuxi',
      'ro.product.board':            'taro',
      'ro.hardware':                 'qcom',
      'ro.build.fingerprint':        'Xiaomi/fuxi/fuxi:13/TKQ1.220905.001/V14.0.2.0.TMCCNXM:user/release-keys',
      'ro.build.description':        'fuxi-user 13 TKQ1.220905.001 V14.0.2.0.TMCCNXM release-keys',
      'ro.build.display.id':         'TKQ1.220905.001',
      'ro.build.id':                 'TKQ1.220905.001',
      'ro.build.version.incremental':'V14.0.2.0.TMCCNXM',
      'ro.build.tags':               'release-keys',
      'ro.build.type':               'user',
      'ro.product.cpu.abi':          'arm64-v8a',
    },
  },

  'pixel-7': {
    id: 'pixel-7',
    label: 'Google Pixel 7',
    brand: 'google',
    manufacturer: 'Google',
    model: 'Pixel 7',
    product: 'panther',
    device: 'panther',
    board: 'pantah',
    hardware: 'tangorpro',
    avdDevice: 'pixel_7',
    screenDpi: 429,
    screenWidth: 1080,
    screenHeight: 2400,
    ram: 8192,
    buildProps: {
      'ro.product.brand':            'google',
      'ro.product.manufacturer':     'Google',
      'ro.product.model':            'Pixel 7',
      'ro.product.name':             'panther',
      'ro.product.device':           'panther',
      'ro.product.board':            'pantah',
      'ro.hardware':                 'tangorpro',
      'ro.build.fingerprint':        'google/panther/panther:13/TQ3A.230605.012/10204971:user/release-keys',
      'ro.build.description':        'panther-user 13 TQ3A.230605.012 10204971 release-keys',
      'ro.build.display.id':         'TQ3A.230605.012',
      'ro.build.id':                 'TQ3A.230605.012',
      'ro.build.version.incremental':'10204971',
      'ro.build.tags':               'release-keys',
      'ro.build.type':               'user',
      'ro.product.cpu.abi':          'arm64-v8a',
    },
  },

  'motorola-g84': {
    id: 'motorola-g84',
    label: 'Motorola Moto G84',
    brand: 'motorola',
    manufacturer: 'motorola',
    model: 'XT2347-1',
    product: 'bangkk',
    device: 'bangkk',
    board: 'taro',
    hardware: 'qcom',
    avdDevice: 'pixel_6',
    screenDpi: 274,
    screenWidth: 1080,
    screenHeight: 2400,
    ram: 8192,
    buildProps: {
      'ro.product.brand':            'motorola',
      'ro.product.manufacturer':     'motorola',
      'ro.product.model':            'XT2347-1',
      'ro.product.name':             'bangkk',
      'ro.product.device':           'bangkk',
      'ro.product.board':            'taro',
      'ro.hardware':                 'qcom',
      'ro.build.fingerprint':        'motorola/bangkk/bangkk:13/T2SRS33M.67-19-3/4ab95:user/release-keys',
      'ro.build.description':        'bangkk-user 13 T2SRS33M.67-19-3 4ab95 release-keys',
      'ro.build.display.id':         'T2SRS33M.67-19-3',
      'ro.build.id':                 'T2SRS33M.67-19-3',
      'ro.build.tags':               'release-keys',
      'ro.build.type':               'user',
      'ro.product.cpu.abi':          'arm64-v8a',
    },
  },

  'oneplus-11': {
    id: 'oneplus-11',
    label: 'OnePlus 11',
    brand: 'OnePlus',
    manufacturer: 'OnePlus',
    model: 'CPH2449',
    product: 'salami',
    device: 'salami',
    board: 'kalama',
    hardware: 'qcom',
    avdDevice: 'pixel_6',
    screenDpi: 450,
    screenWidth: 1440,
    screenHeight: 3216,
    ram: 16384,
    buildProps: {
      'ro.product.brand':            'OnePlus',
      'ro.product.manufacturer':     'OnePlus',
      'ro.product.model':            'CPH2449',
      'ro.product.name':             'salami',
      'ro.product.device':           'salami',
      'ro.product.board':            'kalama',
      'ro.hardware':                 'qcom',
      'ro.build.fingerprint':        'OnePlus/salami/salami:13/TP1A.220624.014/P.202301181523:user/release-keys',
      'ro.build.description':        'salami-user 13 TP1A.220624.014 P.202301181523 release-keys',
      'ro.build.display.id':         'TP1A.220624.014',
      'ro.build.id':                 'TP1A.220624.014',
      'ro.build.tags':               'release-keys',
      'ro.build.type':               'user',
      'ro.product.cpu.abi':          'arm64-v8a',
    },
  },
};

module.exports = { DEVICE_PROFILES };
